#!/usr/bin/env sh
#MISE description="Run local server"
#MISE depends=["clean"]

source="$MISE_PROJECT_ROOT/exampleSite"
themeDir=`dirname $MISE_PROJECT_ROOT`

hugo server --buildDrafts --noBuildLock --cleanDestinationDir --watch --source $source --themesDir $themeDir